name: Django Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: 'django-insecure-test-key-for-github-actions'
      DEBUG: 'True'
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      run: |
        python manage.py migrate --settings=clothing_store.settings_prod
        
    - name: Create test data
      run: |
        python create_country_codes.py
        python create_test_users.py
        python create_sample_data.py
        
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput --settings=clothing_store.settings_prod
        
    - name: Run tests
      run: |
        python manage.py test --settings=clothing_store.settings_prod
