# Generated by Django 5.2 on 2025-04-07 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#FF0000', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='ProductLabelRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productlabel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_labels', to='products.product')),
            ],
            options={
                'ordering': ('label__priority',),
                'unique_together': {('product', 'label')},
            },
        ),
    ]
